export const defaultReviewsData = [
  {
    authorName: 'Famille & Voyageurs Francophones',
    authorCity: 'France',
    tourTitle: 'Voyage au Rajasthan 14 Jours',
    title: 'Voyage au Rajasthan 14 Jours',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Janvier 2026',
    comment: 'Bonjour Monsieur Singh, Nous tenons à vous dire à quel point nous avons été ravis par votre organisation : chauffeur exceptionnel, véhicules très confortables, choix des hôtels patrimoniaux magiques et écoute permanente tout au long de notre parcours au Rajasthan.',
    excerpt: '"Bonjour Monsieur Singh, Nous tenons à vous dire à quel point nous avons été ravis par votre organisation : chauffeur exceptionnel, véhicules très confortables, choix des hôtels patrimoniaux magiques et écoute permanente tout au long de notre parcours au Rajasthan."',
    tag: 'Rajasthan • 14 Jours',
    tagIcon: 'fas fa-map-marker-alt',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/07/Voyage-Jaisalmer.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/07/Voyage-Jaisalmer.jpg',
    fallbackImg: '/images/Voyage-Jaisalmer.jpg',
    avatar: 'MS',
    status: 'approved',
    featured: true
  },
  {
    authorName: 'Voyageurs du Ladakh',
    authorCity: 'Genève, Suisse',
    tourTitle: 'Séjour au Ladakh – Le petit Tibet de l\'Inde',
    title: 'Séjour au Ladakh – Le petit Tibet de l\'Inde',
    category: 'ladakh',
    rating: 5,
    travelDate: 'Août 2025',
    comment: 'Le séjour au Ladakh organisé par l\'agence Jodhpur Voyage s\'est déroulé dans les meilleures conditions possibles. Notre chauffeur dans l\'Himalaya était extrêmement fiable, prudent et compétent. Nous avons découvert des monastères bouddhistes uniques et des paysages à couper le souffle.',
    excerpt: '"Le séjour au Ladakh organisé par l\'agence Jodhpur Voyage s\'est déroulé dans les meilleures conditions possibles. Notre chauffeur dans l\'Himalaya était extrêmement fiable, prudent et compétent. Nous avons découvert des monastères bouddhistes uniques et des paysages à couper le souffle."',
    tag: 'Ladakh & Tibet • Circuit Montagne',
    tagIcon: 'fas fa-mountain',
    link: '/tours',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/08/voyage-au-ladakh-inde.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/08/voyage-au-ladakh-inde.jpg',
    fallbackImg: '/images/dest-ladakh.jpg',
    avatar: 'LD',
    status: 'approved',
    featured: true
  },
  {
    authorName: 'Groupe d\'Amis Francophones',
    authorCity: 'Bruxelles, Belgique',
    tourTitle: 'Circuit & Séjour Punjab & Himachal Pradesh',
    title: 'Circuit & Séjour Punjab & Himachal Pradesh',
    category: 'inde-du-nord',
    rating: 5,
    travelDate: 'Mai 2025',
    comment: 'Bonjour M. Singh, Comme convenu je reviens vers vous pour faire un petit point sur notre magnifique voyage au Punjab et dans l\'Himachal Pradesh. Du Temple d\'Or d\'Amritsar aux vallées de Dharamsala, la prise en charge, la sécurité et la flexibilité sur le terrain étaient irréprochables.',
    excerpt: '"Bonjour M. Singh, Comme convenu je reviens vers vous pour faire un petit point sur notre magnifique voyage au Punjab et dans l\'Himachal Pradesh. Du Temple d\'Or d\'Amritsar aux vallées de Dharamsala, la prise en charge, la sécurité et la flexibilité sur le terrain étaient irréprochables."',
    tag: 'Punjab & Himachal Pradesh',
    tagIcon: 'fas fa-place-of-worship',
    link: '/tours',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Voyage-au-Himachal-en-Inde.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Voyage-au-Himachal-en-Inde.jpg',
    fallbackImg: '/images/dest-himachal.jpg',
    avatar: 'PH',
    status: 'approved',
    featured: true
  },
  {
    authorName: 'Chantal & Robert',
    authorCity: 'Toulouse, France',
    tourTitle: 'Séjour au Rajasthan avec Chauffeur Privé',
    title: 'Séjour au Rajasthan avec Chauffeur Privé',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Novembre 2025',
    comment: 'Nous avons particulièrement apprécié l\'organisation impeccable, les voitures spacieuses et toujours climatisées, les chauffeurs d\'une gentillesse rare, le suivi quotidien de l\'agence et les attentions de chaque instant avec les bouteilles d\'eau fournies tous les jours dans le véhicule.',
    excerpt: '"Nous avons particulièrement apprécié l\'organisation impeccable, les voitures spacieuses et toujours climatisées, les chauffeurs d\'une gentillesse rare, le suivi quotidien de l\'agence et les attentions de chaque instant avec les bouteilles d\'eau fournies tous les jours dans le véhicule."',
    tag: 'Chauffeur Privé • Rajasthan',
    tagIcon: 'fas fa-car-side',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Sejour-au-Rajasthan-avec-chauffeur.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Sejour-au-Rajasthan-avec-chauffeur.jpg',
    fallbackImg: '/images/dest-rajasthan.jpg',
    avatar: 'CR',
    status: 'approved',
    featured: true
  },
  {
    authorName: 'Voyageurs Aventuriers',
    authorCity: 'Paris, France',
    tourTitle: 'Voyage au Ladakh (8 Jours)',
    title: 'Voyage au Ladakh (8 Jours)',
    category: 'ladakh',
    rating: 5,
    travelDate: 'Juillet 2025',
    comment: 'Voici le résumé de notre voyage de 8 jours au Ladakh programmé de main de maître par l\'agence Jodhpur Voyage. Mr. Singh a su faire preuve d\'une grande réactivité avant et pendant le parcours. Chaque étape et chaque nuitée en altitude étaient parfaitement planifiées.',
    excerpt: '"Voici le résumé de notre voyage de 8 jours au Ladakh programmé de main de maître par l\'agence Jodhpur Voyage. Mr. Singh a su faire preuve d\'une grande réactivité avant et pendant le parcours. Chaque étape et chaque nuitée en altitude étaient parfaitement planifiées."',
    tag: 'Trek & Aventure • 8 Jours',
    tagIcon: 'fas fa-hiking',
    link: '/tours',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2022/03/voyage-ladakh.jpeg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2022/03/voyage-ladakh.jpeg',
    fallbackImg: '/images/dest-ladakh.jpg',
    avatar: 'VL',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Famille & Amis Francophones',
    authorCity: 'Bordeaux, France',
    tourTitle: 'Rajasthan Hors Sentiers Battus & Taj Mahal',
    title: 'Rajasthan Hors Sentiers Battus & Taj Mahal',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Décembre 2025',
    comment: 'Bonjour, Comme promis nous vous envoyons notre évaluation détaillée : 1. Préparation du voyage : l\'écoute de Mr Singh a permis de composer exactement le voyage personnalisé que nous espérions. 2. Le chauffeur : prévenant et très prudent sur la route. Une expérience magique hors des sentiers battus !',
    excerpt: '"Bonjour, Comme promis nous vous envoyons notre évaluation détaillée : 1. Préparation du voyage : l\'écoute de Mr Singh a permis de composer exactement le voyage personnalisé que nous espérions. 2. Le chauffeur : prévenant et très prudent sur la route. Une expérience magique hors des sentiers battus !"',
    tag: 'Hors des sentiers battus • Taj Mahal',
    tagIcon: 'fas fa-compass',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Voyage-au-Rajasthan-Hors-des-sentiers-battus-avec-Taj-Mahal.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/05/Voyage-au-Rajasthan-Hors-des-sentiers-battus-avec-Taj-Mahal.jpg',
    fallbackImg: '/images/dest-tajmahal.jpg',
    avatar: 'HB',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Voyageurs Passionnés de Culture',
    authorCity: 'Nantes, France',
    tourTitle: 'Voyage Inde du Nord avec Guide Francophone',
    title: 'Voyage Inde du Nord avec Guide Francophone',
    category: 'inde-du-nord',
    rating: 5,
    travelDate: 'Octobre 2025',
    comment: 'Bonjour M. Singh, Comme promis, voici nos impressions chaleureuses sur le voyage. Tout d\'abord merci beaucoup pour nous avoir permis de réaliser ce magnifique périple. Avoir un guide francophone passionné nous a permis de comprendre l\'histoire et les coutumes indiennes au plus près !',
    excerpt: '"Bonjour M. Singh, Comme promis, voici nos impressions chaleureuses sur le voyage. Tout d\'abord merci beaucoup pour nous avoir permis de réaliser ce magnifique périple. Avoir un guide francophone passionné nous a permis de comprendre l\'histoire et les coutumes indiennes au plus près !"',
    tag: 'Guide Francophone • Inde du Nord',
    tagIcon: 'fas fa-user-tie',
    link: '/tours',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-Inde-du-nord_Jodhpur-Voyage.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-Inde-du-nord_Jodhpur-Voyage.jpg',
    fallbackImg: '/images/dest-jodhpur.jpg',
    avatar: 'GF',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Pierre & Hélène Martin',
    authorCity: 'Montpellier, France',
    tourTitle: 'Le Rajasthan & Vallée du Gange à Varanasi',
    title: 'Le Rajasthan & Vallée du Gange à Varanasi',
    category: 'inde-du-nord',
    rating: 5,
    travelDate: 'Février 2026',
    comment: 'Bonjour M. Singh, Désolés pour ce message tardif après notre retour en France. Nous tenions absolument à exprimer notre profonde gratitude envers Jodhpur Voyage. De la majesté d\'Agra aux cérémonies sacrées des ghats de Varanasi, tout était orchestré à la perfection.',
    excerpt: '"Bonjour M. Singh, Désolés pour ce message tardif après notre retour en France. Nous tenions absolument à exprimer notre profonde gratitude envers Jodhpur Voyage. De la majesté d\'Agra aux cérémonies sacrées des ghats de Varanasi, tout était orchestré à la perfection."',
    tag: 'Rajasthan, Agra & Varanasi (Gange)',
    tagIcon: 'fas fa-om',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-inde-du-nord-le-rajasthan-agra-benares.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-inde-du-nord-le-rajasthan-agra-benares.jpg',
    fallbackImg: '/images/dest-varanasi.jpg',
    avatar: 'VG',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Clients Fidèles (2ème Voyage)',
    authorCity: 'Marseille, France',
    tourTitle: 'Voyage au Kerala et Palais de Mysore',
    title: 'Voyage au Kerala et Palais de Mysore',
    category: 'inde-du-sud',
    rating: 5,
    travelDate: 'Décembre 2025',
    comment: 'Nous revenons enchantés d\'un voyage au Kérala organisé par Jodhpur Voyage. Comme pour notre précédent voyage au Rajasthan avec cette même agence locale, l\'accueil, les péniches d\'eau douce (Houseboat) et le palais de Mysore ont comblé toutes nos attentes !',
    excerpt: '"Nous revenons enchantés d\'un voyage au Kérala organisé par Jodhpur Voyage. Comme pour notre précédent voyage au Rajasthan avec cette même agence locale, l\'accueil, les péniches d\'eau douce (Houseboat) et le palais de Mysore ont comblé toutes nos attentes !"',
    tag: 'Kerala & Mysore • Inde du Sud',
    tagIcon: 'fas fa-water',
    link: '/destinations',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-au-Kerala.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-au-Kerala.jpg',
    fallbackImg: '/images/dest-kerala.jpg',
    avatar: 'KM',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Couple de Voyageurs Francophones',
    authorCity: 'Lille, France',
    tourTitle: 'Voyage Rajasthan, Agra & Varanasi',
    title: 'Voyage Rajasthan, Agra & Varanasi',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Novembre 2025',
    comment: 'Nous avons vécu un magnifique voyage à travers le Rajasthan ainsi qu\'à Agra et Varanasi grâce aux conseils avisés de l\'agence Jodhpur Voyage. Un itinéraire rythmé sans aucune fatigue excessive, avec un suivi téléphonique régulier de l\'équipe locale.',
    excerpt: '"Nous avons vécu un magnifique voyage à travers le Rajasthan ainsi qu\'à Agra et Varanasi grâce aux conseils avisés de l\'agence Jodhpur Voyage. Un itinéraire rythmé sans aucune fatigue excessive, avec un suivi téléphonique régulier de l\'équipe locale."',
    tag: 'Rajasthan, Agra & Varanasi',
    tagIcon: 'fas fa-monument',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-au-Rajasthan-et-Taj-Mahal-avec-agence-locale.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/04/Voyage-au-Rajasthan-et-Taj-Mahal-avec-agence-locale.jpg',
    fallbackImg: '/images/image-6.jpg',
    avatar: 'AV',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Monique & Bernard',
    authorCity: 'Rennes, France',
    tourTitle: 'Voyage au Rajasthan 14 Jours',
    title: 'Voyage au Rajasthan 14 Jours',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Mars 2026',
    comment: 'Bonjour Monsieur Singh, Nous voici bien rentrés dans notre commune bien calme. Notre esprit reste rempli de souvenirs précieux et colorés du Rajasthan. Merci pour votre professionnalisme, vos conseils de visite et pour le choix méticuleux des guides dans chaque cité royale.',
    excerpt: '"Bonjour Monsieur Singh, Nous voici bien rentrés dans notre commune bien calme. Notre esprit reste rempli de souvenirs précieux et colorés du Rajasthan. Merci pour votre professionnalisme, vos conseils de visite et pour le choix méticuleux des guides dans chaque cité royale."',
    tag: 'Circuit 14 Jours • Rajasthan',
    tagIcon: 'fas fa-calendar-alt',
    link: '/tour-rajasthan',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/03/voyage-au-rajasthan-inde.jpeg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/03/voyage-au-rajasthan-inde.jpeg',
    fallbackImg: '/images/dest-rajasthan.jpg',
    avatar: 'RJ',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Voyageuses Fidèles (3ème Séjour)',
    authorCity: 'Strasbourg, France',
    tourTitle: 'Séjour au Gujarat avec Guide Francophone',
    title: 'Séjour au Gujarat avec Guide Francophone',
    category: 'gujarat',
    rating: 5,
    travelDate: 'Février 2026',
    comment: 'Bonjour M. Singh, Nous sommes bien rentrées de notre tour au Gujarat. C\'est le 3ème voyage consécutif que nous confions à votre agence locale ! Comme toujours, l\'organisation était irréprochable et la découverte des tribus du Gujarat était inoubliable.',
    excerpt: '"Bonjour M. Singh, Nous sommes bien rentrées de notre tour au Gujarat. C\'est le 3ème voyage consécutif que nous confions à votre agence locale ! Comme toujours, l\'organisation était irréprochable et la découverte des tribus du Gujarat était inoubliable."',
    tag: 'Gujarat • 3ème Voyage',
    tagIcon: 'fas fa-city',
    link: '/destinations',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/03/Sejour-au-Gujarat.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2026/03/Sejour-au-Gujarat.jpg',
    fallbackImg: '/images/dest-gujarat.jpg',
    avatar: 'GJ',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Deux Amis Aventuriers',
    authorCity: 'Lyon, France',
    tourTitle: 'Voyage Exceptionnel Ladakh & Zanskar',
    title: 'Voyage Exceptionnel Ladakh & Zanskar',
    category: 'ladakh',
    rating: 5,
    travelDate: 'Septembre 2025',
    comment: 'Nous étions deux amis et souhaitions faire un voyage précis au Zanskar et Ladakh. Nous avons soumis notre itinéraire exigeant à Mr. Singh qui a orchestré la logistique de chaque col de montagne, des jeeps 4x4 et des hébergements de manière fabuleuse.',
    excerpt: '"Nous étions deux amis et souhaitions faire un voyage précis au Zanskar et Ladakh. Nous avons soumis notre itinéraire exigeant à Mr. Singh qui a orchestré la logistique de chaque col de montagne, des jeeps 4x4 et des hébergements de manière fabuleuse."',
    tag: 'Zanskar & Ladakh • Hautes Altitudes',
    tagIcon: 'fas fa-snowflake',
    link: '/tours',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2025/11/zanskar.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2025/11/zanskar.jpg',
    fallbackImg: '/images/dest-ladakh.jpg',
    avatar: 'LZ',
    status: 'approved',
    featured: false
  },
  {
    authorName: 'Famille Moreau (5 personnes)',
    authorCity: 'Nice, France',
    tourTitle: 'Voyage en Famille Rajasthan & Taj Mahal',
    title: 'Voyage en Famille Rajasthan & Taj Mahal',
    category: 'rajasthan',
    rating: 5,
    travelDate: 'Octobre 2025',
    comment: 'Bonjour Monsieur Singh, Nous vous remercions pour le magnifique séjour et les merveilleuses découvertes effectués avec nos trois enfants. L\'attention portée à la sécurité de la famille et le confort des véhicules minibus étaient exceptionnels !',
    excerpt: '"Bonjour Monsieur Singh, Nous vous remercions pour le magnifique séjour et les merveilleuses découvertes effectués avec nos trois enfants. L\'attention portée à la sécurité de la famille et le confort des véhicules minibus étaient exceptionnels !"',
    tag: 'Voyage Famille • Rajasthan & Taj Mahal',
    tagIcon: 'fas fa-users',
    link: '/voyage-sur-mesure',
    image: 'https://www.jodhpurvoyage.com/wp-content/uploads/2025/11/Voyage-en-famille-en-Inde.jpg',
    img: 'https://www.jodhpurvoyage.com/wp-content/uploads/2025/11/Voyage-en-famille-en-Inde.jpg',
    fallbackImg: '/images/image-12.jpg',
    avatar: 'FA',
    status: 'approved',
    featured: false
  }
];

export const reviewsData = defaultReviewsData;
