export const defaultSeoData = [
  {
    pageKey: 'home',
    pageName: "Page d'Accueil (Home)",
    customUrl: '/',
    title: 'Jodhpur Voyage - Agence de Voyage & Tour Opérateur en Inde et Népal',
    description: 'Créateur de voyages sur mesure d’exception au Rajasthan, Inde du Nord, Inde du Sud et Népal. Plus de 20 ans d’expérience avec guides francophones et chauffeurs privés.',
    keywords: 'voyage inde, agence voyage rajasthan, tour operateur inde, circuit rajasthan sur mesure, jodhpur voyage, voyage nepal francophone, chauffeur prive inde',
    ogTitle: 'Jodhpur Voyage - Agence de Voyage d’Exception en Inde et Népal',
    ogDescription: 'Partez à la découverte des palais de maharajas, taj mahal, backwaters du Kerala et montagnes du Népal avec notre agence locale francophone.',
    ogImage: '/images/dest-rajasthan.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/',
    structuredData: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'TravelAgency',
      'name': 'Jodhpur Voyage',
      'url': 'https://jodhpurvoyage.com',
      'logo': 'https://jodhpurvoyage.com/images/logo-transprent.png',
      'description': 'Agence de voyage spécialiste des circuits sur mesure en Inde et Népal',
      'telephone': '+91-9650698669',
      'email': 'Info@jodhpurvoyage.com',
      'address': {
        '@type': 'PostalAddress',
        'addressLocality': 'Jodhpur',
        'addressRegion': 'Rajasthan',
        'addressCountry': 'IN'
      },
      'priceRange': '€€€'
    })
  },
  {
    pageKey: 'tours',
    pageName: 'Circuits & Tours Accompagnés',
    customUrl: '/tours',
    title: 'Circuits & Voyages Accompagnés en Inde et Népal | Jodhpur Voyage',
    description: 'Découvrez nos itinéraires privés d’exception : Rajasthan Doré, Triangle d’Or, Kerala Backwaters, Ladakh et Katmandou. Tarifs et devis gratuits.',
    keywords: 'circuits inde, circuits rajasthan, voyage accompagne inde, itineraire rajput, voyage sur mesure inde',
    ogTitle: 'Circuits & Voyages Accompagnés en Inde | Jodhpur Voyage',
    ogDescription: 'Consultez nos itinéraires de circuits privés en Inde du Nord, Rajasthan, Inde du Sud et Népal.',
    ogImage: '/images/jaipur-travel.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/tours',
    structuredData: ''
  },
  {
    pageKey: 'destinations',
    pageName: 'Nos Destinations (Rajasthan, Kerala, Népal...)',
    customUrl: '/destinations',
    title: 'Destinations de Voyage en Inde & Népal | Jodhpur Voyage',
    description: 'Explorez nos régions coup de cœur : Rajasthan, Inde du Nord, Kerala, Tamil Nadu, Ladakh, Gujarat et Népal. Conseils pour bien préparer votre voyage.',
    keywords: 'destinations inde, rajasthan voyage, kerala tourisme, ladakh trek, nepal voyage',
    ogTitle: 'Toutes Nos Destinations de Rêve en Inde et Népal',
    ogDescription: 'Explorez la beauté du Rajasthan, du Kerala, de l’Himalaya et des temples sacrés.',
    ogImage: '/images/dest-kerala.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/destinations',
    structuredData: ''
  },
  {
    pageKey: 'voyage-sur-mesure',
    pageName: 'Voyage 100% Sur Mesure',
    customUrl: '/voyage-sur-mesure',
    title: 'Créer Votre Voyage Sur Mesure en Inde | Devis Gratuit под 24h',
    description: 'Concevez votre itinéraire personnalisé selon vos envies, dates et budget. Formulaire simple, conseils d’experts francophones et devis 100% gratuit.',
    keywords: 'voyage sur mesure inde, circuit personnalise rajasthan, devis voyage inde gratuit, agence sur mesure inde',
    ogTitle: 'Créez Votre Itinéraire Unique sur Mesure en Inde',
    ogDescription: 'Faites votre demande de devis sur mesure gratuit en 2 minutes.',
    ogImage: '/images/slide8-300x176.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/voyage-sur-mesure',
    structuredData: ''
  },
  {
    pageKey: 'commentaires',
    pageName: 'Avis Clients & Témoignages',
    customUrl: '/commentaires',
    title: 'Avis & Témoignages Voyageurs | Jodhpur Voyage (TripAdvisor, Trustpilot)',
    description: 'Découvrez les retours d’expérience et commentaires authentiques de nos voyageurs ayant exploré l’Inde et le Népal avec nos chauffeurs et guides.',
    keywords: 'avis jodhpur voyage, temoignages voyage inde, avis agence voyage rajasthan, avis tripadvisor jodhpur voyage',
    ogTitle: 'Avis & Témoignages de nos Voyageurs en Inde',
    ogDescription: 'Plus de 20 ans de sourires et de retours enthousiastes sur TripAdvisor, Trustpilot et Google.',
    ogImage: '/images/tripadvisor-badge.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/commentaires',
    structuredData: ''
  },
  {
    pageKey: 'blog',
    pageName: 'Blog & Conseils de Voyage',
    customUrl: '/blog',
    title: 'Blog Voyage Inde & Népal - Conseils, Culture & Guides | Jodhpur Voyage',
    description: 'Articles, conseils pratiques, guides culturels, formalités de visa et secrets de voyage pour réussir votre aventure en Inde et au Népal.',
    keywords: 'blog voyage inde, conseils partir inde, culture rajasthan, guide tourisme inde, formalites visa inde',
    ogTitle: 'Blog & Articles de Voyage sur l’Inde et le Népal',
    ogDescription: 'Tous nos articles et secrets de voyage rédigés par nos spécialistes locaux.',
    ogImage: '/images/blog-culture.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/blog',
    structuredData: ''
  },
  {
    pageKey: 'qui-nous-sommes',
    pageName: 'Qui Nous Sommes',
    customUrl: '/qui-nous-sommes',
    title: 'Qui Sommes Nous ? Notre Histoire & Agence Locale | Jodhpur Voyage',
    description: 'Découvrez l’histoire de Jodhpur Voyage, agence pionnière spécialiste du voyage sur mesure francophone en Inde et au Népal depuis plus de 20 ans.',
    keywords: 'qui sommes nous jodhpur voyage, agence locale francophone inde, equipe jodhpur voyage',
    ogTitle: 'À Propos de Jodhpur Voyage - Votre Agence Locale Francophone',
    ogDescription: 'Notre passion du voyage sur mesure authentique en Inde.',
    ogImage: '/images/image-12.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/qui-sommes-nous',
    structuredData: ''
  },
  {
    pageKey: 'notre-equipe',
    pageName: 'Notre Équipe',
    customUrl: '/notre-equipe',
    title: 'Notre Équipe Francophone & Chauffeurs Dédiés | Jodhpur Voyage',
    description: 'Rencontrez l’équipe passionnée de Jodhpur Voyage : conseillers francophones, chauffeurs professionnels expérimentés et guides certifiés.',
    keywords: 'equipe jodhpur voyage, chauffeurs indiens francophones, guides voyage rajasthan',
    ogTitle: 'Rencontrez l’Équipe de Jodhpur Voyage',
    ogDescription: 'Nos spécialistes à votre service pour un séjour parfait.',
    ogImage: '/images/image-8.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/notre-equipe',
    structuredData: ''
  },
  {
    pageKey: 'infos-pratiques',
    pageName: 'Infos Pratiques & Visa',
    customUrl: '/infos-pratiques',
    title: 'Infos Pratiques, Visa, Climat & Budget Inde | Jodhpur Voyage',
    description: 'Tout ce qu’il faut savoir avant de partir : demande de visa e-Visa, meilleures périodes (climat), monnaie (rupie), santé, vaccins et conseils.',
    keywords: 'infos pratiques inde, visa inde, quand partir rajasthan, budget voyage inde, monnaie rupie inde',
    ogTitle: 'Guide Pratique pour Voyageurs en Inde & Népal',
    ogDescription: 'Informations essentielles sur le visa, la santé, le climat et les devises.',
    ogImage: '/images/visas-banner.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/infos-pratiques',
    structuredData: ''
  },
  {
    pageKey: 'contact',
    pageName: 'Page Contact',
    customUrl: '/contact',
    title: 'Contactez-Nous - Agence Jodhpur Voyage à Jodhpur (Rajasthan)',
    description: 'Une question, un projet de circuit ? Contactez nos experts francophones par téléphone, email, WhatsApp ou via notre formulaire de contact.',
    keywords: 'contact jodhpur voyage, telephone jodhpur voyage, email agence inde, whatsapp jodhpur voyage',
    ogTitle: 'Contactez nos Conseillers Francophones Jodhpur Voyage',
    ogDescription: 'Nous répondons à toutes vos questions sous 24h.',
    ogImage: '/images/contact-banner.jpg',
    canonicalUrl: 'https://jodhpurvoyage.com/contact',
    structuredData: ''
  }
];
